### ISSUE TITLE
Plural is "Paths", not "Pathes" (configPathes)

### ISSUE THREAD

**Issue by fnogatz** [rolfn/node-gitlab-hook#4]
Spelling mistake in config option `configPathes`.

**Comment by WuglyakBolgoink** [comment]
https://www.dictionary.com/browse/path

![image](https://user-images.githubusercontent.com/2271337/66118734-69f67680-e5d7-11e9-95c8-566134c26801.png)

**Comment by rolfn** [comment]
I do not support this software anymore.
